### ISSUE TITLE
Change threshold of the detection

### ISSUE THREAD

**Issue by saran13raj** [juandes/tensorflowjs-objectdetection-tutorial#3]
Hi
How can i reduce the threshold so that the confidence level can range from 0.3 to 1?

**Comment by juandes** [comment]
Hi,

To reduce the confidence level use the parameter `minScore` from the `model.detect()` function.

This is the function's signature:

```
model.detect(
  img: tf.Tensor3D | ImageData | HTMLImageElement |
      HTMLCanvasElement | HTMLVideoElement, maxNumBoxes: number, minScore: number
)
```

You can find more information at [https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd).

Hope this helps!
